### ISSUE TITLE
Some general questions

### ISSUE THREAD

**Issue by AvivSham** [threedworld-mit/tdw#122]
Hi All,
Thank you and well done for developing such a great simulation tool!
I have a few related questions:

-  Which graphic engine do you use under the hood? (e.g. Maya, UE, Blender, Unity)
- What are the audio rendering abilities of this simulation? Does it support doppler effect \ impulse response?
- Is it possible to anchor a pair of microphones to a specific object? 
- Do you support multiple microphones and sound sources in a single scene?

Thanks in advance.

**Comment by instbldrjems** [comment]
@AvivSham 

We use Unity. 

You can see examples of our audio capabilities on the web site (www.threedworld.org). We support audio spatialization and localization using Resonance Audio, as well as real-time synthesis of impact sounds based on object mass, material, collision behaviors (see paper reference on web site). TDW has several example and use case controllers that use our audio capabilities, and they are fully documented on the repo:

https://github.com/threedworld-mit/tdw/blob/master/Documentation/misc_frontend/impact_sounds.md

We support multiple sound sources in a scene (there is an example of that in our example controllers).  We do not support multiple audio listeners on a single avatar; given we support binaural sound I'm not sure what the point of that would be.  We have never tried >1 audio-enabled avatars in a scene; that is an interesting idea and something we should probably try.

**Comment by instbldrjems** [comment]
> We have never tried >1 audio-enabled avatars in a scene; that is an interesting idea and something we should probably try.
Actually, probably can't do this -- I don't think Unity supports more than one audio listener in a scene.
