### ISSUE TITLE
`add_fixed_joint` to be deprecated?

### ISSUE THREAD

**Issue by danielbear** [threedworld-mit/tdw#151]
I noticed that the `add_fixed_joint` command to attach one object to another is deprecated and slated for removal, though it hasn't been removed yet.

Is there another command that will replace it? Being able to rigidly attach two objects is a useful feature.

**Comment by alters-mit** [comment]
I found it to be rather buggy when paired with the Sticky Mitten Avatar. Are you using it? Are there any problems with objects "stretching" or snapping away from each other?

**Comment by danielbear** [comment]
I've only tried using it to stick two objects together (e.g. a cube with a
pole sticking out), not with an avatar. I haven't encountered any bugs so
far -- the two objects seem to behave as a single compound object. But I'll
keep an eye out for that.
