### ISSUE TITLE
Feature request: singularity file

### ISSUE THREAD

**Issue by guhur** [threedworld-mit/tdw#169]
Hi,

Clusters tend not to support docker, but Singularity containers, which are less powerful -- and thus less dangerous.

Could you share a Singularity definition file?
A few tools exist for converting a Dockerfile into a Singularity definition file, but it will contain a few mistakes.

I can create such file once I will be more familiarized with TDW.

Thanks!

**Comment by subalterngames** [comment]
@guhur I'm unfamiliar with Singularity but if you write a definition file I'll try testing it.

**Comment by alters-mit** [comment]
Closing because this isn't a feature that will be implemented in TDW LTS
