### ISSUE TITLE
Unexpected white cube during generation

### ISSUE THREAD

**Issue by eliaszwang** [threedworld-mit/tdw#180]
![image](https://user-images.githubusercontent.com/8966246/116952403-6f96c100-ac3f-11eb-9235-f7a5c4c26673.png)
TDW version: 1.8.7
Player.log file:
`Mono path[0] = 'C:/Users/eliwang/tdw_build/TDW/TDW_Data/Managed'
Mono config path = 'C:/Users/eliwang/tdw_build/TDW/MonoBleedingEdge/etc'
Initialize engine version: 2020.2.7f1 (c53830e277f1)
[Subsystems] Discovering subsystems at path C:/Users/eliwang/tdw_build/TDW/TDW_Data/UnitySubsystems
[Subsystems] No descriptors matched for  examples in UnitySubsystems/OculusXRPlugin/UnitySubsystemsManifest.json.
[Subsystems] 1 'inputs' descriptors matched in UnitySubsystems/OculusXRPlugin/UnitySubsystemsManifest.json
[Subsystems] 1 'displays' descriptors matched in UnitySubsystems/OculusXRPlugin/UnitySubsystemsManifest.json
[Subsystems] No descriptors matched for  meshings in UnitySubsystems/OculusXRPlugin/UnitySubsystemsManifest.json.
[Subsystems] No descriptors matched for  examples in UnitySubsystems/WindowsMRXRSDK/UnitySubsystemsManifest.json.
[Subsystems] 1 'inputs' descriptors matched in UnitySubsystems/WindowsMRXRSDK/UnitySubsystemsManifest.json
[Subsystems] 1 'displays' descriptors matched in UnitySubsystems/WindowsMRXRSDK/UnitySubsystemsManifest.json
[Subsystems] 1 'meshings' descriptors matched in UnitySubsystems/WindowsMRXRSDK/UnitySubsystemsManifest.json
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 (ID=0x1b80)
    Vendor:   
    VRAM:     8079 MB
    Driver:   27.21.14.5671
Begin MonoManager ReloadAssembly
- Completed reload, in  0.124 seconds
XRGeneral Settings awakening...

D3D11 device created for Microsoft Media Foundation video decoding.
[XR] OculusXRPlugin: registering subsystems
[Subsystems] OculusXRPlugin successfully registered Provider for oculus display
[XR] Oculus Input lifecycle provider registered.
[Subsystems] OculusXRPlugin successfully registered Provider for oculus input
[Subsystems] OculusXRPlugin successfully registered Provider for oculus display
<RI> Initializing input.

XInput1_3.dll not found. Trying XInput9_1_0.dll instead...
<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.235900 ms
Setting up 24 worker threads for Enlighten.
  Thread -> id: 64dc -> priority: 1 
  Thread -> id: 7654 -> priority: 1 
  Thread -> id: 9e5c -> priority: 1 
  Thread -> id: 96fc -> priority: 1 
  Thread -> id: 99b4 -> priority: 1 
  Thread -> id: 247c -> priority: 1 
  Thread -> id: 8bec -> priority: 1 
  Thread -> id: 70ac -> priority: 1 
  Thread -> id: 8a04 -> priority: 1 
  Thread -> id: a6e0 -> priority: 1 
  Thread -> id: 90a0 -> priority: 1 
  Thread -> id: a3c8 -> priority: 1 
  Thread -> id: 2bf8 -> priority: 1 
  Thread -> id: a334 -> priority: 1 
  Thread -> id: 6f34 -> priority: 1 
  Thread -> id: a688 -> priority: 1 
  Thread -> id: 92ec -> priority: 1 
  Thread -> id: 3154 -> priority: 1 
  Thread -> id: 8c8c -> priority: 1 
  Thread -> id: 4a1c -> priority: 1 
  Thread -> id: 5780 -> priority: 1 
  Thread -> id: 2388 -> priority: 1 
  Thread -> id: 9f28 -> priority: 1 
  Thread -> id: 8fd4 -> priority: 1 
Object cube isn't a cached object. [TDW.CollisionStayListener]

Object cube isn't a cached object. [TDW.CollisionStayListener]

Object cube isn't a cached object. [TDW.CollisionStayListener]

Object cube isn't a cached object. [TDW.CollisionStayListener]

Object cube isn't a cached object. [TDW.CollisionStayListener]

Object cube isn't a cached object. [TDW.CollisionStayListener]

Object with ID 1 already exists in the cache. This object has been given a new ID: -968722629 [TDW.ProcGenSceneRoot]

ArgumentException: An item with the same key has already been added. Key: 1
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000c1] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at TDW.ProcGenSceneRoot.CacheObject (TDW.CachedObjectBase c) [0x00000] in <0692d6301a894e8d861ae9b3bb7ed472>:0 
  at TDW.ProcGenSceneRoot.CacheModel (TDW.CachedModel c) [0x00000] in <0692d6301a894e8d861ae9b3bb7ed472>:0 
  at TDWInput.AddModelCommand.End (UnityEngine.GameObject obj) [0x000c6] in <0692d6301a894e8d861ae9b3bb7ed472>:0 
  at TDWInput.AddObject.End (UnityEngine.GameObject obj) [0x00000] in <0692d6301a894e8d861ae9b3bb7ed472>:0 
  at TDWInput.AssetBundleCommand`1+<DownloadAssetBundle>d__16[T].MoveNext () [0x0008f] in <0692d6301a894e8d861ae9b3bb7ed472>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <5f528563e9f04651878c6c899feba4b9>:0 
UnityEngine.MonoBehaviour:StartCoroutineManaged2(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
TDWInput.AssetBundleCommand`1:Do()
NetworkManager:Unpack(NetMQMessage&)
Req:Update()

`

**Comment by instbldrjems** [comment]
@eliaszwang Please post your controller in the Slack channel.
