### ISSUE TITLE
What is the capacity of container?

### ISSUE THREAD

**Issue by yashkant** [threedworld-mit/tdw#190]
Hi, 

I am looking for a detail that I did not find in the original paper -- what is the capacity of the containers that the agent can use to carry multiple objects? Is it infinite, a fixed value, or anything else? 

--- 
Thanks,
Yash

**Comment by alters-mit** [comment]
I updated the Transport Challenge documentation to include information about container capacity and object size: https://github.com/alters-mit/transport_challenge/commit/dccf8f4feb86f5fb2cd9e283f03fba577b95c98e
