### ISSUE TITLE
./TDW.x86_64 exists without any information

### ISSUE THREAD

**Issue by caiqi** [threedworld-mit/tdw#191]
Running ./TDW.x86_64 exists immediately without any information.  ``c = Controller()`` hangs forever at `self.socket.recv()`. The system is Ubuntu 18 and tdw is installed with `pip install tdw.` Is there any way to debug into such cases? Thanks!

**Comment by alters-mit** [comment]
`c = Controller()` will automatically launch the build. This is probably why it's hanging.

What is the output of this controller?

```python
from tdw.controller import Controller

c = Controller(launch_build=False)
print("ok!")
c.communicate({"$type": "terminate"})
```

(note that you'll need to launch TDW.x86_64 after launching this script)

**Comment by YuzheSHI** [comment]
I've tested the assignments for the two arguments of `Controller()`. When `launch_build = False`, the Unity window would not work. However, when `launch_build = True`, it only works when enabling private network proxy even if `check_version` is set as `False`. All the other trails return nothing and it is weird that _TDW_ here cannot entirely run offline. It's very nice of you if you can figure out any solution and let us know.

**Comment by alters-mit** [comment]
When `launch_build=False` what happens when you try to launch TDW.x86_64?

> All the other trails return nothing and it is weird that TDW here cannot entirely run offline. 

Most of the scenes and models in TDW are stored on a remote S3 server. It's possible though somewhat difficult to use them offline. To do this:

1. Download the models and scenes you want to use. See: [ModelLibrarian](https://github.com/threedworld-mit/tdw/blob/master/Documentation/python/librarian/model_librarian.md) and [SceneLibrarian](https://github.com/threedworld-mit/tdw/blob/master/Documentation/python/librarian/scene_librarian.md) Below is an example script to help you get started:

```python
from requests import get
from pathlib import Path
from tdw.librarian import ModelLibrarian

p = Path.home().joinpath("tdw_models")
if not p.exists():
    p.mkdir(parents=True)
lib = ModelLibrarian()

# Print the name of every model.
for record in lib.records:
    print(record.name)

# Download models.
models = ["iron_box", "rh10"]
for model in models:
    record = lib.get_record(model)
    resp = get(record.urls["Linux"])
    assert resp.status_code == 200, f"Tried to download {model} but got status code {resp.status_code}"
    p.joinpath(model).write_bytes(resp.content)
```

2. Create a controller that loads models in from local files:

```python
from pathlib import Path
from tdw.controller import Controller
from tdw.tdw_utils import TDWUtils
from tdw.librarian import ModelLibrarian

lib = ModelLibrarian()
p = Path.home().joinpath("tdw_models")
c = Controller(launch_build=False, check_version=False, udp=False)
c.start()

commands = [TDWUtils.create_empty_room(12, 12)]
models = ["iron_box", "rh10"]
x = 0
object_id = 0
for model in models:
    filepath = str(p.joinpath(model).resolve())
    record = lib.get_record(model)
    commands.append({"$type": "add_object",
                     "name": model,
                     "url": "file:///" + filepath,
                     "scale_factor": record.scale_factor,
                     "position": {"x": x, "y": 0, "z": 0},
                     "rotation": {"x": 0, "y": 0, "z": 0},
                     "category": record.wcategory,
                     "id": object_id})
    x += 1.5
    object_id += 1
```

Let me know if that helps.
