### ISSUE TITLE
tactile simluation integration/support

### ISSUE THREAD

**Issue by shivanimall** [threedworld-mit/tdw#193]
Hello, 

thank you for this rich-featured interactive simulation engine. 

I am wondering if there are any plans for supporting tactile simulations?
For example: integrating it/supporting tactile simulator like TACTO (https://github.com/facebookresearch/tacto)

**Comment by AlanHsu94** [comment]
Hi, 
I'm looking forward to this new feature! 
Is there anything I can help with?

**Comment by jemsMIT** [comment]
@AlanHsu94 Thank you for your offer of help. I think it is a bit early for us to discuss that, but as we formulate our plan we will reach out to you again.  We are interested in getting input from those with experience using haptics and tactile simulation, as to what capabilities would be useful in the context of TDW.  Feel free to post any thoughts here. Same goes for you @shivanimall

**Comment by shivanimall** [comment]
thanks @jemsMIT, would love to see support for soft body simulation to capture material dependent deformation. For example: I have a glass object(A), a wooden object(B) and a rubber-like object (C) - all equal sized, curvature and mass. That is only material differs. With the same force F at point X on obj (C) we would expect to see a larger deformation than we would see in obj (A) or (B). 
Would be great this material-dependent deformation and differences in tactile depth maps readings captured as a result.

**Comment by alters-mit** [comment]
Closing because this isn't a feature that will be implemented in TDW LTS
