### ISSUE TITLE
no /Python folder for pip installation

### ISSUE THREAD

**Issue by FishAres** [threedworld-mit/tdw#2]
I may be missing something obvious, but upon extracting the TDW folder for Windows or Linux, there is no Python folder from which to run pip install. 

On Windows the tree is :
├───MonoBleedingEdge
│   ├───EmbedRuntime
│   └───etc
│       └───mono
│           ├───2.0
│           │   └───Browsers
│           ├───4.0
│           │   └───Browsers
│           ├───4.5
│           │   └───Browsers
│           └───mconfig
└───TDW_Data
    ├───Managed
    ├───Plugins
    └───Resources

And on Linux:
└───TDW_Data
    ├───Managed
    ├───MonoBleedingEdge
    │   ├───etc
    │   │   └───mono
    │   │       ├───2.0
    │   │       │   └───Browsers
    │   │       ├───4.0
    │   │       │   └───Browsers
    │   │       ├───4.5
    │   │       │   └───Browsers
    │   │       ├───mconfig
    │   │       └───registry
    │   └───x86_64
    ├───Plugins
    │   └───x86_64
    └───Resources

None of the subfolders contain anything I've found that python can play with. Help pls? :)

**Comment by alters-mit** [comment]
Hi @FishAres sorry for the confusion. We just updated to v1.6.1 which has a much more streamlined installation process (sorry we couldn't quite get this done in time for our initial release!)

- All you need now is to `pip3 install tdw`. Then, follow the updated [getting started guide](https://github.com/threedworld-mit/tdw/blob/master/Documentation/getting_started.md).
- You can download/fork the repo to use our example controllers.
- The files that you were looking through are the _release_ zip files, the are the binary executables that handle the simulation environment. The repo's Python source code (which again, you don't necessarily even need anymore) is always located in these files:

![image](https://user-images.githubusercontent.com/37152170/88426824-d1c4ba80-cdbf-11ea-9eb3-3b8b0d6f6e64.png)

**Comment by FishAres** [comment]
@alters-mit awesome, thank you!
