### ISSUE TITLE
Create composite object with different mass/friction.. for each subobject

### ISSUE THREAD

**Issue by gaobaoding** [threedworld-mit/tdw#238]
Dear authors,

Thanks for your great work, it looks quite interesting. Before I decide to use it in my work, I'm wondering if I can use it to create some random composite object and assign each subpart with different mass, friction, etc.. And maybe ultimately I can export the composite object into a single file (urdf, xml or whatever). I see there is a part about composite objects in the documentation, but not really answer my question.

Thanks in advance :)

**Comment by alters-mit** [comment]
You can! Composite objects are just Unity prefabs. We don't have a standard pipeline for setting up the prefab but if you're familiar with Unity Editor, you can easily adjust the mass and physic materials of each sub-object before creating an asset bundle from the prefab.

Our models are stored as "asset bundle" binaries, not URDF or XML. It's possible in Unity Editor to export a prefab to URDF but you wouldn't be able to use it in TDW.

TDW _does_ support the opposite case--converting an existing URDF into an asset bundle. See: https://github.com/threedworld-mit/tdw/blob/master/Documentation/python/robot_creator.md
