### ISSUE TITLE
Unexpected behavior for some object models

### ISSUE THREAD

**Issue by mdb293** [threedworld-mit/tdw#257]
Hello. I'm trying to place a stationary object in the center of a room and take pictures of it from a camera circling the room and looking at it. For many object models this works fine (like the wood_chair):
![wood_chair](https://user-images.githubusercontent.com/19844295/130866062-ae7074b9-1902-4885-b23d-0e73eccd0de8.gif)

But some object models, like backpack, round_bowl_large_metal_perf, poliform_park_low_arm_sofa, and bed01_red show unexpected behavior, like the object intersecting with the floor or moving around.

![backpack](https://user-images.githubusercontent.com/19844295/130866827-b513bbfa-664e-4ee1-9154-8a69ddd6c211.gif)
![round_bowl_large_metal_perf](https://user-images.githubusercontent.com/19844295/130866274-006a3d99-70a1-4500-81d6-b86b0c307b1f.gif)
![poliform_park_low_arm_sofa](https://user-images.githubusercontent.com/19844295/130866277-473549a9-d01a-4a5c-b223-f965e133ce88.gif)
![bed01_red](https://user-images.githubusercontent.com/19844295/130866284-d71758de-1c47-4740-a4bb-85e4c9a4a90a.gif)

Here is the simple script that produces these results:

```
import os
import csv
import math
import json
from tqdm import tqdm


from pathlib import Path
from tdw.controller import Controller
from tdw.tdw_utils import TDWUtils
from tdw.librarian import ModelLibrarian
from tdw.output_data import OutputData, Bounds, Images, Collision, EnvironmentCollision

num_frames = 50
dimensions = [10, 10]

lib = ModelLibrarian(library="models_core.json")

name = "backpack"#"round_bowl_large_metal_perf" "poliform_park_low_arm_sofa" "bed01_red"

c = Controller(launch_build=True)
c.communicate({"$type": "set_render_quality", "render_quality": 3})
c.communicate({"$type": "simulate_physics", "value": True})
c.communicate({"$type": "set_time_step", "time_step": 1})

resp = c.communicate([{"$type": "load_scene", "scene_name": "ProcGenScene"},
TDWUtils.create_empty_room(*dimensions)])

x = 0
y = 0
z = 0
resp = c.communicate([c.get_add_object(model_name = name, object_id = 0, position = {"x": x, "y": y, "z": z})])

avatar_id = "a"
resp = c.communicate([{"$type": "create_avatar",
"type": "A_Img_Caps_Kinematic",
"avatar_id": avatar_id},
{"$type": "look_at",
"avatar_id": avatar_id,
"object_id": 0},
{"$type": "set_pass_masks",
"avatar_id": avatar_id,
"pass_masks": ["_img"]}])

radius = 3
angles = [2*math.pi * i/num_frames for i in range(num_frames)]

for frame in range(num_frames):
    angle = angles[frame]
    camera = {"x": radius * math.cos(angle), "y": 2.5, "z": radius * math.sin(angle)}
    resp = c.communicate([{"$type": "teleport_avatar_to", "position": camera, "avatar_id": avatar_id},
                          {"$type": "look_at","avatar_id": avatar_id, "object_id": 0},
                          {"$type": "send_images", "frequency": "once"}])

    for r in resp:
        r_id = OutputData.get_data_type_id(r)
        if r_id == "imag":
            img = Images(r)

            TDWUtils.save_images(img, filename=f"{name}_{frame:03}")

c.communicate({"$type": "terminate"})
```

I am using the latest version of TDW (version 1.8.24). We would appreciate an insight into what it going on. Thanks!

**Comment by mdb293** [comment]
@alters-mit 
That mostly works, thank you! The "poliform_park_low_arm_sofa" is still sunk into the floor even with physics turned off, but the other objects are fine.


A follow-up question: we ultimately want to generate scenes with randomly selected objects at random positions in the room, but not overlapping with one another. To do that, we've been using collision detection:

`resp = c.communicate([{"$type": "send_collisions", "stay": True}])`

and then relocating an object while there are still collisions.

```
while collisions:
    for col in collisions:
        x = random.uniform(-(dimensions[0]/2 - 2), dimensions[0]/2 - 2)
        z = random.uniform(-(dimensions[1]/2 - 2), dimensions[1]/2 - 2)

        x_1 = random.uniform(-(dimensions[0]/2 - 2), dimensions[0]/2 - 2)
        z_1 = random.uniform(-(dimensions[1]/2 - 2), dimensions[1]/2 - 2)
        collider = col.get_collider_id()
        collidee = col.get_collidee_id()
        print(f"collision between objects {collider}, {collidee}")
        angle_1 = random.uniform(0, 360)
        resp = c.communicate([{"$type": "teleport_object", "id": collider, "position": {"x": x, "y":
            placement_height, "z": z}},
                              {"$type": "teleport_object", "id": collidee, "position": {"x": x_1, "y":
                                  placement_height, "z": z_1}},
                              {"$type": "rotate_object_to_euler_angles", "euler_angles": {"x": 0, "y": angle, "z": 0}, "id": collider},
                              {"$type": "rotate_object_to_euler_angles", "euler_angles": {"x": 0, "y": angle_1, "z":
                                  0}, "id": collidee}])
        resp = c.communicate({"$type": "send_collisions", "stay": True})

    # refresh col and b
    collisions = []
    for r in resp:
        r_id = OutputData.get_data_type_id(r)
        print(r_id)
        if r_id == "coll":
            collisions.append(Collision(r))

```

This doesn't work with physics turned off. Is there something else they you would recommend instead of collision detection for making sure that the objects don't overlap with each other?

Thanks!

**Comment by alters-mit** [comment]
Try sending [`set_kinematic_state`](https://github.com/threedworld-mit/tdw/blob/master/Documentation/api/command_api.md#set_kinematic_state) for each object.
