### ISSUE TITLE
RobotArm example does not launch the build.

### ISSUE THREAD

**Issue by Orbif0ld** [threedworld-mit/tdw#271]
Hi,
First of all, thanks for making this awesome tool public!

What happens:
Running [example_controllers/robot_arm.py ](https://github.com/threedworld-mit/tdw/blob/master/Python/example_controllers/robot_arm.py) hangs, failing to display the robot arm. There is no error.

Probable cause:
launch_build is set to False:
`if __name__ == "__main__":
    RobotArm(launch_build=False).run()`

[Suggested fix.](https://github.com/threedworld-mit/tdw/pull/272)

**Comment by alters-mit** [comment]
Closing this ticket. [See comment on PR](https://github.com/threedworld-mit/tdw/pull/272).
