### ISSUE TITLE
How does engine parse the commands and play the audio

### ISSUE THREAD

**Issue by sunwell1994** [threedworld-mit/tdw#286]
Hi, I have one question in get_audio_commands(). It detects the collision and generates the impact sound by get_audio_commands(). It is executed by every frame, which is 0.01s in the setup. The default sampling rate is 44100.
I try to log the generated sound in each frame as below and find something confusing. Each generated sound is an impact response, but how to concatenate them is at the engine side.

1.  each frame can generate more than 44100*0.01=440 samples. How do you concatenate these samples?
2.  One collision can be detected in consecutive frames, such as 53 and 54. How do you concatenate these frames?
```
frame number53, the wave shape (8502,)
frame number54, the wave shape (8781,)
frame number88, the wave shape (8696,)
frame number92, the wave shape (8762,)
frame number93, the wave shape (9214,)
frame number99, the wave shape (8701,)
frame number109, the wave shape (8514,)
frame number110, the wave shape (8550,)
frame number111, the wave shape (8759,)
frame number112, the wave shape (8616,)
frame number114, the wave shape (8704,)
frame number115, the wave shape (8610,)
frame number119, the wave shape (8871,)
frame number123, the wave shape (8863,)
frame number124, the wave shape (9031,)
frame number126, the wave shape (8716,)```

**Comment by alters-mit** [comment]
We have documentation [here](https://github.com/threedworld-mit/tdw/blob/master/Documentation/misc_frontend/video.md) for how to record synchronized video and audio. 

If you haven't done so already, add a `set_target_framerate` command so that the physics engine is more synchronized with the audio output rate.
