### ISSUE TITLE
Issue in adding a robot

### ISSUE THREAD

**Issue by deepang1712** [threedworld-mit/tdw#295]
Hello,

I tried to add a robot using the following code: [Robot Librarian](https://github.com/threedworld-mit/tdw/blob/master/Documentation/python/librarian/robot_librarian.md#command-api), But I ran into a build error. Could someone please explain what I am doing wrong?

Here is the log file: [Log File](https://drive.google.com/file/d/1ZWJJmVYridlAF52TCHq-jgkIsbTsRK8y/view?usp=sharing)

**Comment by alters-mit** [comment]
@deepang1712 

We just released TDW 1.9.0 which improves the user-end robotics API.

[Read this for more information.](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/robots/overview.md)

[This document has an overall v1.8 -> v1.9 upgrade guide.](https://github.com/threedworld-mit/tdw/blob/master/Documentation/upgrade_guides/v1.8_to_v1.9.md)
