### ISSUE TITLE
Accurate Collision detection

### ISSUE THREAD

**Issue by sunwell1994** [threedworld-mit/tdw#299]
It is really cool that the tool can give collision detection at the frame level, i.e. the Collision object can tell whether there is a collision inside this frame with the contact position, relative velocity, etc. 

However, How can we get the accurate timestamp of the collision enter and exit state? Thanks.

**Comment by alters-mit** [comment]
@sunwell1994 

```python
from time import time
from tdw.controller import Controller
from tdw.tdw_utils import TDWUtils
from tdw.output_data import OutputData


c = Controller()
c.start()
resp = c.communicate([TDWUtils.create_empty_room(12, 12),
                      c.get_add_object("iron_box",
                                       object_id=0,
                                       position={"x": 0, "y": 1.5, "z": 0}),
                      {"$type": "send_collisions"}])
collisions = {}
for i in range(100):
    for j in range(len(resp) - 1):
        r_id = OutputData.get_data_type_id(resp[j])
        if r_id == "coll":
            collisions[i] = time()
    resp = c.communicate([])
```

**Comment by sunwell1994** [comment]
> @sunwell1994
> 
> ```python
> from time import time
> from tdw.controller import Controller
> from tdw.tdw_utils import TDWUtils
> from tdw.output_data import OutputData
> 
> 
> c = Controller()
> c.start()
> resp = c.communicate([TDWUtils.create_empty_room(12, 12),
>                       c.get_add_object("iron_box",
>                                        object_id=0,
>                                        position={"x": 0, "y": 1.5, "z": 0}),
>                       {"$type": "send_collisions"}])
> collisions = {}
> for i in range(100):
>     for j in range(len(resp) - 1):
>         r_id = OutputData.get_data_type_id(resp[j])
>         if r_id == "coll":
>             collisions[i] = time()
>     resp = c.communicate([])
> ```

Thanks for your answer. But time() here cannot capture the collision time in the simulation. The accuracy is still at the frame level.

**Comment by alters-mit** [comment]
@sunwell1994 Time is paused between frames. Nothing can occur between communicate() calls. For collision data, we almost always log the frame number (in this case, `i`), rather than a time stamp.

**Comment by sunwell1994** [comment]
> @sunwell1994 Time is paused between frames. Nothing can occur between communicate() calls. Unless there is significant lag in your Internet connection, there is no difference between calling `time()` in the Python code and the "actual" time of the collision. For collision data, we almost always log the frame number (in this case, `i`), rather than a time stamp.

Got it. It is based on the frame number to update the collision information.
I encounter some other problems.
1. Can we set framerate to 1000 fps?
2. g = 9.81m/s^2 in Unity engine. I have compared the init position, velocity, and contact points. It seems that based on 1/2 * g * t ^ 2, it is impossible to reach the contact points. Are there any other constants not to be considered? Thanks.

**Comment by alters-mit** [comment]
It is usually impossible to reach 1000 FPS. 100 FPS is typical for an average use-case. Read [this](https://github.com/threedworld-mit/tdw/blob/master/Documentation/benchmark/benchmark.md) and [this](https://github.com/threedworld-mit/tdw/blob/master/Documentation/benchmark/performance_optimizations.md) for more information.
