### ISSUE TITLE
Ways/Feature to draw shapes/lines in TDW

### ISSUE THREAD

**Issue by xf-zhao** [threedworld-mit/tdw#300]
Hello, thank you all for the constantly update.

In robotic manipulations we always want to create customed tasks using some special markers as a source of guidelines. I have noticed that TDW have a built-in `add_position_marker` function to do similar things. But as I tested, the shape is quite limited, and more importantly we can not precisely control the radius of the pre-defined circle shape (the parameter `scale` does not make much sense to users who want to do something like "set a circle with radius 0.1", I tried setting `scale=0.1` but it did not work as I expected.)

Also, I noticed that the `marker` is designed for debugging purpose. But can we actually implement some functions to draw precise shapes (which should also be captured by a vision avartar for post-processing) in TDW?

Thank you very much!

**Comment by xf-zhao** [comment]
Update for the `scale` parameter:
after several attempts, now I realize that `scale` controls diameter (not ridius). I would like to suggest an update to the related document. But the question "whether we can draw lines" still remains. Looking forward to seeing  your plan.

**Comment by alters-mit** [comment]
@xf-zhao I'll update the documentation. Are there other shapes that you'd like to be able to use?
