### ISSUE TITLE
How to run "Controller" and "KeyboardController" at the same time?

### ISSUE THREAD

**Issue by yding25** [threedworld-mit/tdw#305]
Hi,

I have created an environment including adding some objects, loading a scene using **"Controller()"**.
I want to use keyboards to watch the scenario. I am trying to use **"KeyboardController"**. 
But it shows that "Address already in use". I guess I cannot put these two controller functions together.
Are there some approaches to solve this conflict?

**Comment by alters-mit** [comment]
@yding25 We just released TDW 1.9.0

[This document explains how to add keyboard controls to any controller.](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/humans/keyboard.md)

[This document has an overall v1.8 -> v1.9 upgrade guide.](https://github.com/threedworld-mit/tdw/blob/master/Documentation/upgrade_guides/v1.8_to_v1.9.md)
