### ISSUE TITLE
Possibility of supporting setups without X?

### ISSUE THREAD

**Issue by auroracramer** [threedworld-mit/tdw#306]
Hi! First of all, thanks for the amazing library you've put out! I was wondering if there was any possibility that the dependency on X server could be removed at some point, or if there's any known workarounds? I'd like to run this on our HPC cluster, but as users we don't have permission to start our own X-servers. Thanks!

**Comment by alters-mit** [comment]
Closing this ticket. The underlying Unity Engine requires X.
