### ISSUE TITLE
"set_joint_targets" bug: Fetch robot cannot arrive at the targeted position.

### ISSUE THREAD

**Issue by yding25** [threedworld-mit/tdw#343]
I use "set_joint_targets" for wheel links to task the Fetch robot to achieve a position.
But I find if the target value is big (e.g., 7200), the robot will stop running **at some point** unexpectedly, and cannot arrive at the targeted position.
I do not know why the Fetch robot has such an issue.
I find the motion control of the Fetch robot is unreliable, especially for the wheel link.

By the way, are the high-level APIs for motion planners, such as reaching for a location for the wheel-based robots? There are not many such examples.

**Comment by alters-mit** [comment]
@yding25 [See my response here.](https://github.com/threedworld-mit/tdw/issues/341)

> By the way, are the high-level APIs for motion planners, such as reaching for a location for the wheel-based robots? There are not many such examples.

Magnebot has a high-level wheel API.
