### ISSUE TITLE
/var/log/auth.log grows too fast

### ISSUE THREAD

**Issue by xf-zhao** [threedworld-mit/tdw#353]
hello,

I observed that after run some experiments the log file `/var/log/auth.log` grew too fast and have achieved to an up to 19GB in my case, many of the logs is like:

```bash
Jan 22 06:59:14 xxxxxx dbus-daemon[936]: [system] Rejected: destination has a full message queue, 0 matched rules; type="error", sender="(unset)" ((bus)) interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="1" destination=":1.10347" (uid=38015 pid=7491 comm="/home/zhao/tdw_build/TDW/TDW.x86_6" label="unconfined")
Jan 22 06:59:14 xxxxxx dbus-daemon[936]: [system] Rejected: destination has a full message queue, 0 matched rules; type="error", sender="(unset)" ((bus)) interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="1" destination=":1.10369" (uid=38015 pid=27875 comm="/home/zhao/tdw_build/TDW/TDW.x86_6" label="unconfined")
```
(I substitued the machine id with xxxxxx above for privacy concern.)

It caused a full-disk crash then, and after I deleted this log, I found that it grows very fast again. 

To make it clear, here is some extra information:

- I use Ubuntu-18.04 ( 5.4.0-94-generic, x86_64 GNU/Linux)
- I run TDW in a headless server (using Xorg and specify $DISPLAY)
- TDW works well and no clear strange things have happened (until  the disk was full of log, then it crashed)
- sometimes I use pycharm remote debuging. Most of the time I ssh to server and run TDW by python scripts
- I simulated for about 1M frames, the `auth.log` grew to ~1GB size; I trained 3 env using 3 Gpus, after 300K frames, `auth.log` now grows to ~3GB size. And since it is located at `/var/log/`, it will cause some issue beyond my control.
- I am monitoring `auth.log` but I am not sure when it will grow dramatically (sometimes it remains a unchanged size for a while)

So my questions are: 
1. Is this normal or something goes wrong in my setting?
2. How can I disable this kind of log from the TDW aspect (because I do not have root permission of this machine and I cannot easily delete `auth.log` by myself).

Thank you very much in advance!

**Comment by alters-mit** [comment]
@xf-zhao TDW doesn't generate a file named `auth.log`.

[This site suggests that the problem might be NVIDIA.](https://forums.developer.nvidia.com/t/bug-nvidia-v495-29-05-driver-spamming-dbus-enabled-applications-with-invalid-messages/192892)

You should try upgrading your NVIDIA drivers.

**Comment by alters-mit** [comment]
Closed due to inactivity
