### ISSUE TITLE
always waiting in socket.recv()

### ISSUE THREAD

**Issue by rainbow979** [threedworld-mit/tdw#36]
I tried to follow getting_started.md in my laptop, but it waited in 

> File "my.py", line 3, in <module>
>     c = Controller()
>   File "/home/sy/.local/lib/python3.6/site-packages/tdw/controller.py", line 51, in __init__
>     self.socket.recv()
>   File "zmq/backend/cython/socket.pyx", line 791, in zmq.backend.cython.socket.Socket.recv
>   File "zmq/backend/cython/socket.pyx", line 827, in zmq.backend.cython.socket.Socket.recv
>   File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
>   File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc

What's the problem?

**Comment by alters-mit** [comment]
@rainbow979 What version of TDW are you using? If you are using 1.6.0, try upgrading to the latest version of TDW and running your controller again.

> And I want to know what would happen if I directly run ./tdw.x86_64

v1.6.1 onward, you can launch  ./tdw.x86_64 ("the build") and it will wait for a message from the controller, provided that `launch_build == False`

Option A:

```python
from tdw.controller import Controller

c = Controller()
```

Result: The controller launches the build and sends an initial message.

Option B:

```python
from tdw.controller import Controller

c = Controller(launch_build=False)
```
and 

```bash
 ./TDW.x86_64
```

Result: The controller launches. The build launches. The controller sends an initial message.
