### ISSUE TITLE
Feature request: headless rendering

### ISSUE THREAD

**Issue by Aubret** [threedworld-mit/tdw#376]
Hi,

I'm currently using threedworld on clusters with Xvfb and singularity, but it is impossible to take advantage of GPUs for rendering since it requires a xorg server, which is usually not provided by clusters administrators. The builds is considerably slower (15 times in one of my setting) when it uses cpu.

Do you plan to make threedworld compatible with headless servers ?

It looks like [ai2thor found a way to do this with unity ](https://blog.allenai.org/ai2-thor-partners-with-unity-to-enable-headless-multi-node-training-in-the-cloud-571802be5ad3 ), but I'm not sure how they do this.

Thanks,

**Comment by instbldrjems** [comment]
Hi --

We have been planning to investigate this for a while, and will be doing so as soon as possible.  We will need to evaluate what is involved, and what the potential costs are. There are no commitments as to outcome or time frame, but we will keep you informed.

**Comment by Aubret** [comment]
Hi,

I looked forward advances with respect to this issue so I'm happy it's "solved". Did I miss a part of the documentation that explains how to do it ?? I upgraded my version but did not manage to do it without cpu rendering.

Best
