### ISSUE TITLE
“C# Source Code for TDW”, I think it goes against the spirit of open source, or pseudo open source

### ISSUE THREAD

**Issue by smallverse** [threedworld-mit/tdw#413]
[C# Source Code for TDW](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/misc/c_sharp_sources.md)

 **I think it goes against the spirit of open source, or pseudo open source, for the following reasons：**

1. If you're understaffed, I think the community is strong and enthusiasts can contribute
2. If you don't trust some commercial companies, you can adopt a stricter open source license instead of the MIT 'license

thanks！

**Comment by instbldrjems** [comment]
HI --

Due to some recent changes to the TDW backend involving non-free third- party code, we are currently reevaluating our policies regarding  access to the TDW C# sources but cannot make them available at the present time.  We hope to resolve this situation in the near future.

Thank you.

**Comment by smallverse** [comment]
thanks！

**Comment by smallverse** [comment]
> HI --
> 
> Due to some recent changes to the TDW backend involving non-free third- party code, we are currently reevaluating our policies regarding access to the TDW C# sources but cannot make them available at the present time. We hope to resolve this situation in the near future.
> 
> Thank you.

thanks！
I see. Maybe buying a custom version of Unity's engine
