### ISSUE TITLE
It took so long to download the floorplan and assets from remote server

### ISSUE THREAD

**Issue by tmatuan-smu** [threedworld-mit/tdw#424]
Hi there,

May I ask if there is a way to download and store the floorplan and asset bundle locally, since it took so long to download them and then get discarded from memory after the code stop. If not, what is the alternative solution? when I need to preview the objects placement in a particular floorplan layout. 

Thanks,

**Comment by alters-mit** [comment]
You can! [Read this for more information.](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/misc/download_asset_bundles.md)
