### ISSUE TITLE
Is it possible to grasp a cup in VR?

### ISSUE THREAD

**Issue by Glanfaloth** [threedworld-mit/tdw#435]
Hi, I was trying to grasp a cup with Oculus. As shown below, as soon as I clench, the fingers penetrates through the handle and the cup falls onto the ground. When I try to grasp a cup on the table, I always grasp the table instead. Is there a way I can hold the handle of the cup?
![1](https://user-images.githubusercontent.com/52867627/166115367-b05d6345-dd11-4d9c-9311-a14b1930c248.gif)
![2](https://user-images.githubusercontent.com/52867627/166115372-9c148d10-f95b-4e73-9be8-d6826062c6cb.gif)

**Comment by alters-mit** [comment]
Either make the table non-graspable (`non_graspable=[table_id]`) in the constructor and in `reset()`) or make the table kinematic (which will automatically make it non-graspable)

https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/vr/oculus_touch.md#graspable-objects
