### ISSUE TITLE
Speaker position

### ISSUE THREAD

**Issue by YandongJi** [threedworld-mit/tdw#454]
When I play with audio.py and setting the speaker position to 1000 meters away using
```
object_position_0 = {"x": 1000, "y": 1, "z": 1}
audio_initializer.play(path="HWL_1b.wav", position=object_position_0)
```
I can still hear the sound clearly and cannot distinguish differences if I set the speaker at x=1 meter. Is this expected?
Also it seems like they are the same for the speakers at left and right side of the audio agent.

**Comment by instbldrjems** [comment]
No, this is not expected behavior. Thank you for bringing this to our attention. We will look into this asap.

**Comment by alters-mit** [comment]
Not a bug. `audio.py` doesn't use Resonance Audio and so this is expected behavior. See: `resonance_audio.py`

**Comment by instbldrjems** [comment]
However we will update `audio.py` to use only a single "speaking: object, to remove any possible confusion.

**Comment by YandongJi** [comment]
Not so sure if I did something wrong. But I cannot run resonance_audio.py successfully. Actually for each example containing ResonanceAudioInitializer, such as ```impact_with_controller.py, minimal_audio_dataset.py, reset_by_impact.py, resonance_audio.py, robot_impact_sound.py, scrape_with_controller.py```. Each time after I add "ResonanceAudioInitializer" to add-on and run communicate(), the build will quit. Specifically in communicate(), after ```self.socket.send_multipart(msg)```, I cannot get ```resp = self.socket.recv_multipart()``` working.
Thank you. :)

**Comment by alters-mit** [comment]
Make sure that you've killed all controller processes and all build processes and try again.

**Comment by YandongJi** [comment]
Just copied [player log](https://docs.google.com/document/d/1eF-kmdC4V86AGl_hN6NR5q0dK0cWBUwUlIRjJ1LrXTs/edit?usp=sharing) here. Is this an expected output?

**Comment by alters-mit** [comment]
I just ran `resonance_audio.py` on Ubuntu 20 using TDW 1.9.17 and it worked without any errors in the changelog.

What distro are you running? What is the output of this:

```python
from tdw.version import __version__
print(__version__)
```

**Comment by alters-mit** [comment]
I think the problem is due to this error in the log:

```
__google_auxv version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
```

I don't know much about c compiling but I think `GLIBC_PRIVATE` is the relevant part.

https://groups.google.com/g/uk.comp.os.linux/c/PX3rstGtZRQ

**Comment by YandongJi** [comment]
Thanks for helping Seth! A turnaround on Ubuntu 18.04 for me could be downgrading [audiosdk](https://github.com/resonance-audio/resonance-audio-unity-sdk/issues/51#issuecomment-427579766) from 1.2.1 to 1.2.0. I attach its repo [here](https://github.com/resonance-audio/resonance-audio-unity-sdk/releases). Just downloading [ResonanceAudioForUnity_1.2.0_source.zip](https://github.com/resonance-audio/resonance-audio-unity-sdk/releases/download/v1.2.0/ResonanceAudioForUnity_1.2.0_source.zip) would be enough. The turnaround is adding ```audiopluginresonanceaudio.dll``` to ```~/tdw_build/TDW/TDW_Data/Managed/``` and replacing ```libaudiopluginresonanceaudio.so``` with the version of 1.2.0. And it works!
