### ISSUE TITLE
unstableness of high-level APIs

### ISSUE THREAD

**Issue by yding25** [threedworld-mit/tdw#470]
Hi,

I utilized the high-level APIs (v1.9.17), such as grabbing and releasing an item.
I discovered that certain APIs were unstable. For instance, Magnetbots consistently failed when attempting to hold a cup on a table.
According to my own experience, the collision between the robot arm and the table and the lack of reactions contributed to the failure.
Is there any solutions to improve the success rate of motion planning?

By the way, Magnetbot performed well when grasping an object from the floor, where there is no any obstacles. 

Best,
Yan

**Comment by alters-mit** [comment]
Closing this issue. This is a known limitation of Magnebot. [Read this for more information.](https://github.com/alters-mit/magnebot/blob/main/doc/manual/magnebot/arm_articulation.md)
