### ISSUE TITLE
Control multiple FirstPersonAvatar

### ISSUE THREAD

**Issue by kiototeko** [threedworld-mit/tdw#486]
Hello,

I was wondering if there was a way of controlling multiple instances of FirstPersonAvatar so as to allow multiple users to interact in a single scenario concurrently? 

E.g. making users connect to a server process with their own personal computers and interact in the same simulated scenario.

Thanks

**Comment by alters-mit** [comment]
@kiototeko Right now, TDW doesn't support multiple personal computers. It's a very complex problem that would require a lot of development time.

**Comment by kiototeko** [comment]
Thank you for you reply!
