### ISSUE TITLE
Could we do screen-off simulation now?

### ISSUE THREAD

**Issue by LuZeking** [threedworld-mit/tdw#508]
Hi,

Thanks for developing this excellent platform, I am using it now for a scientific project.

Everything works fine when I choose "launch_build = True", but when I set it as false, the programs just stuck in waiting there and I still need to manually launch the TDW.exe in Windows. But the "Screen-off" is vital to my project since I tend to move the project to the remote Linux servers for training, where the X-server is unavailable. 

I noticed in another "feature request" issue, you said that you are developing headless rendering, may I ask about your progress and course release time?  Because if it still needs a long time to go, I have to change my plan.

Or do we have an alternative way to do "screen-off" simulation before this feature release?

**Comment by alters-mit** [comment]
Unfortunately this is not possible. The underlying Unity engine requires a display.

[This document explains how to run TDW on a virtual display, which still requires X.](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/setup/install.md)
