### ISSUE TITLE
get_depth_values causes overflow

### ISSUE THREAD

**Issue by dsp05** [threedworld-mit/tdw#52]
The `depth_shader.py` example does not render correct depth.

https://github.com/threedworld-mit/tdw/blob/8ad5c33acd64e33ede198734973d04f1a09e8919/Python/tdw/tdw_utils.py#L382

`image.dtype` is `uint8` by default, which causes overflow when multiplying 256*256 

`` image = np.array(Image.open(io.BytesIO(image)), dtype="uint32") `` could solve the issue.

**Comment by alters-mit** [comment]
@dsp05 See this PR: https://github.com/threedworld-mit/tdw/pull/53

Let me know if the depth values are indeed correct.
