### ISSUE TITLE
 Can we add custom human models? 

### ISSUE THREAD

**Issue by jmtree** [threedworld-mit/tdw#526]
We hope to add some human objects. Can we add custom human models? Can we use the animations like run, walk ?

**Comment by alters-mit** [comment]
You can add custom non-physics humanoids. [Read this.](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/non_physics_humanoids/custom_humanoids.md)

You can add custom animations for physics-based Replicants and non-physics humanoids. [Read this.](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/non_physics_humanoids/custom_animations.md)
