### ISSUE TITLE
Controller Port Already in Use

### ISSUE THREAD

**Issue by mustafaadogan** [threedworld-mit/tdw#528]
Hello guys,

I want to create and render more than one scene in my controller file. For that reason, I am creating Controller object in a for loop of my scenes. In that loop, I send my commands through controller.communicate(). At the end of scene, I send terminate command. The problem here is if I gave a constant port number while creating my Controller object, then I take Address is Already in Use error. Probably the previous socket is not closed yet. How can I close that socket? If I do not create Controller object in the for loop and use only one object, then my scenes except first one are not rendered by the build. How can I create and render multiple scenes one by one?

**Comment by alters-mit** [comment]
This error is caused when you don't close a controller or build process. Make sure that they're all closed and try again.

To render multiple scenes sequentially, you should reuse the same controller and build and unload/reload scenes. [Read this for more information.](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/scene_setup_high_level/reset_scene.md)
