### ISSUE TITLE
Issue with launching the build on a remote ssh server

### ISSUE THREAD

**Issue by dkukul19** [threedworld-mit/tdw#553]
Hello,
I am trying to run tdw to generate scenes and save their images on my university's remote server. However, I cannot get the build to launch; the program gets stuck at the line where the Controller is initialized. I'm running the example code given here (https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/core_concepts/images.md), which works fine on my local computer. I am unable to fully follow the instructions given at (https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/setup/install.md#install-tdw-on-a-remote-linux-server) as I don't have permission to generate xorg.conf (/etc/X11/xorg.conf) file, and I don't have sudo privileges either. When I run the program, a small window named TDW (same as the build) pops up for a brief second on XQuarts on my local screen but it disappears and the program runs indefinitely until I manually terminate it. I would appreciate any help. Thanks in advance.

**Comment by alters-mit** [comment]
Unfortunately you do need to have X running on your server. Once you have X running, you need to set `launch_build=False` in your controller and then launch your build manually on the server: https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/core_concepts/launch_build.md

**Comment by dkukul19** [comment]
Is there a way I can generate the scenes and save their images without displaying the build? I only need the images of the scenes, is there a way I can do this efficiently?
