### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by onlyonewater** [threedworld-mit/tdw#569]
hi, authors, great work, when I read the paper, I noticed that you created a dataset with 1.3M images to do the Visual recognition transfer task, could you have a plan to release this dataset? thanks!

**Comment by onlyonewater** [comment]
and I want to know if I can use the tdw simulator to render the object of different colors?

**Comment by alters-mit** [comment]
> could you have a plan to release this dataset?

We don't host the dataset. You can generate similar to the one in the paper with this tool: https://github.com/alters-mit/tdw_image_dataset

>  render the object with different colors

[`set_color`](https://github.com/threedworld-mit/tdw/blob/master/Documentation/api/command_api.md#set_color)

> different sizes

[`scale_object`](https://github.com/threedworld-mit/tdw/blob/master/Documentation/api/command_api.md#scale_object)

> different camera positions

Read [this](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/core_concepts/avatars.md) and [this](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/camera/overview.md).

> different lighting

Read [this](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/photorealism/lighting.md) and [this](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/photorealism/interior_lighting.md).

**Comment by onlyonewater** [comment]
ok, thanks!!! your detailed answer is very helpful.
