### ISSUE TITLE
About nav_mesh.py example with magnebot

### ISSUE THREAD

**Issue by junmokane** [threedworld-mit/tdw#657]
Hi, I tried to execute the code from nav_mesh.py in tdw/Python/example_controllers/navigation,

and I just executed the original code while the magnebot is not moving toward to target position. 
I used the exactly same code and I checked that `path` and point `p` in path gives the following output when printed.

`Your installed tdw Python module is up to date with PyPi.`
`Build version 1.12.16`
`Unity Engine 2020.3.24f1`
`Python tdw module version 1.12.16.0`
`Images will be saved to: /home/jmcho/project/tdw/nav_mesh_original`
`[[ 0.1         0.07842962 -1.3       ]
 [-1.0000005   0.07842962 -0.666667  ]
 [-2.          0.07842962  4.        ]]`
`{'x': -1.0000004768371582, 'y': 0, 'z': -0.6666669845581055}`
`{'x': -2.0, 'y': 0, 'z': 4.0}`

The code just executes well, while the visualization results show that no movement from magnetbot. It just stays in initial position. Should there be some modifications to use move_to function in magnebot in current repo version? I checked that simple test code for MagnebotController for move_by(2) executes well, and the position is moved accurately. Thanks for the hard work!

**Comment by alters-mit** [comment]
Hi, I just wanted to say that I'm working on this but this isn't a simple fix. 

> So, I just commented this line and related lines. Would this affect the thing that I observed in above problem?
You'll need to comment out a few more lines and it's safe to do so. They just handle version checking. I've already fixed this part of the problem in a test branch.

**Comment by alters-mit** [comment]
Fixed. Upgrade to the latest version of `magnebot` (2.2.8).
