### ISSUE TITLE
Add force in the middle

### ISSUE THREAD

**Issue by justlovebarbecue** [threedworld-mit/tdw#697]
Thanks for this great project!

A quick question, is there a way to add a force in the middle of the simulation? current doc says that we can add a force at beginning (a time point) or a constant one (all the time during simulation). Is there a way to make it in the middle?

Thanks!

**Comment by alters-mit** [comment]
Yes. Any of the `apply_force_` commands can be used at any time: https://github.com/threedworld-mit/tdw/blob/master/Documentation/api/command_api.md#apply_force_to_object
