### ISSUE TITLE
Whether you can use PyQT to create your own GUI

### ISSUE THREAD

**Issue by zanxueyan** [threedworld-mit/tdw#712]
Many thanks to the project development team for sharing. 
In the actual use of the process, through twd_build as a GUI display, can not do any operation, I look forward to being able to design my own application through pyqt, I do not know if you can provide relevant examples or documentation, very much looking forward to.
If it is not possible to combine with pyqt, are there other solutions to develop your own applications using twd? 
Look forward to your reply and support, thank you!

**Comment by alters-mit** [comment]
It's possible to use pyqt with a TDW Python controller because the TDW Python controller is just a Python class that can be used with any other Python script.

It isn't possible to use pyqt in the TDW build because it's built in Unity C#, not Python.

**Comment by zanxueyan** [comment]
Thank you very much for your reply! Can I provide a simple demo? If it's convenient for you. Thank you

**Comment by zanxueyan** [comment]
Maybe I did not make it clear, because the build provided by the official is not open source, so it is inconvenient to create the interface and software functions you need by yourself. I hope to use pyQT as the rendering engine and interface to replace the build downloaded by the official default. I don't know if I can do that. @alters-mit 
Why do I ask this question, because considering that build can render and execute animation after receiving commands, if pyQT or other rendering engines are used as the interface, it is necessary to create the same function of build, parse commands and execute corresponding rendering and functions in order to be effective?

**Comment by alters-mit** [comment]
It is *technically* possible to use a different rendering engine, but you would have to essentially rewrite the entire simulation codebase of TDW.
