### ISSUE TITLE
When Unity window is not visible, output turns out black or "white noise"-like

### ISSUE THREAD

**Issue by colobas** [threedworld-mit/tdw#78]
I'm trying to use TDW to generate an image dataset, similar to one of your described use-cases. In my current setup, I don't always start X with access to my graphics card, so as to save battery when I'm not using it. But since image rendering is faster on the GPU, I start a tty with a GPU-enabled X session. I start the script, see the Unity window pop-up, see some images being generated, all good so far. 

I then switch to another tty (running a different X session, not GPU-enabled), leaving the script running in the GPU-enabled tty. The images that are generated while I'm on the GPU-less tty turn out black or like gaussian noise.

Does the Unity window always need to be visible while rendering?

**Comment by alters-mit** [comment]
@colobas Check you player log, which should be located at `~/.config/unity3d/MIT/TDW/Player.log` on the same machine as the Unity executable. If there are OpenGL Errors, try this fix: https://github.com/threedworld-mit/tdw/blob/master/Documentation/misc_frontend/debug_tdw.md#open-gl-error

Let me know if that works.

**Comment by colobas** [comment]
After a package update in my environment, I'm unable to reproduce the error. I'm closing the issue. Thank you for your help!
